name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run cs fixer
      run: ./vendor/bin/php-cs-fixer fix

    - name: Run php stan
      run: ./vendor/bin/phpstan analyse --level 8 src tests

    - name: Run cs fixer
      run: ./vendor/bin/phpunit --colors=always --coverage-html coverage tests
